clean:
	rm -rf *.o *.a *_test
check_format:
	clang-format -style=LLVM -i `find -regex ".+\.[ch]"` --dry-run --Werror
format:
	clang-format -style=LLVM -i `find -regex ".+\.[ch]"`
task1.o: task1.c task1.h
	gcc -g -c task1.c -o task1.o 
task1.a: task1.o
	ar rc task1.a task1.o 
main_test.o: main_test.c
	gcc -g -c main_test.c -o main_test.o -lm
task1_test: main_test.o task1.a
	gcc -g -static -o task1_test main_test.o task1.a -lm
test1: task1_test
	./task1_test
